/* Program.cs
 * 
 * Default main generated by Visual Studio, 
 * it is the entry program to the application
 * 
 * Created By: Ankit Sadana
 * Created On: 12/02/2014
 * Last Modified By: Ankit Sadana
 * Last Modified On: 12/04/2014
 * IU Username: asadana
 * 
 * Assignment #3 for A590
 * Part of: RPNCalculator Project
 */

// Libraries being used for this Form
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

// Project name: RPNCalculator
namespace RPNCalculator
{
    // Main class for this program
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        // Main method for this application
        static void Main()
        {
            // Default functions by visual studio
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            // Creating and running the form application frmRPNCalculator
            Application.Run(new frmRPNCalculator());
        }
    }
}
